apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
  labels:
    app: traefik-ingress
data:
  traefik.toml: |
    # Global settings
    [global]
      checkNewVersion = false
      sendAnonymousUsage = false
    # Servers transport settings
    [serversTransport]
      insecureSkipVerify = true
    # Entrypoints settings
    [entryPoints]
      [entryPoints.http]
        address = ":80"
      [entryPoints.https]
        address = ":443"
      [entryPoints.traefik]
        address = ":8080"
      [entryPoints.monitoring]
        address = ":9090"
    # Logs settings
    [log]
      level = "ERROR"
      format = "json"
    [accessLog]
      format = "json"
    # API dashboard settings
    [api]
      dashboard = true
      debug = false
      insecure = true
    # Monitoring settings
    [ping]
      entryPoint = "monitoring"
    # Providers settings
    [providers]
      [providers.kubernetesCRD]
    # Metrics settings
    [metrics]
      [metrics.prometheus]
        addEntryPointsLabels = true
        addServicesLabels = true
        entryPoint = "traefik"
    # Certificates settings
    [certificatesResolvers]
      # Environment production
      [certificatesResolvers.letsencrypt]
        [certificatesResolvers.letsencrypt.acme]
          email = "email@domain.tld"
          storage = "/certs/letsencrypt.json"
          caServer = "https://acme-v02.api.letsencrypt.org/directory"
          [certificatesResolvers.letsencrypt.acme.httpChallenge]
            entryPoint = "http"
      # Environment staging
      [certificatesResolvers.letsencrypt-staging]
        [certificatesResolvers.letsencrypt-staging.acme]
          email = "email@domain.tld"
          storage = "/certs/letsencrypt-staging.json"
          caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
          [certificatesResolvers.letsencrypt-staging.acme.httpChallenge]
            entryPoint = "http"
