apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-certs
  namespace: kube-system
  labels:
    app: traefik-ingress
spec:
  capacity:
    storage: 32Mi
  accessModes:
    - ReadWriteMany
