apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-authentication
  namespace: kube-system
type: Opaque
stringData:
  # account is: traefik/traefik
  traefik-dashboard-authentication: traefik:$apr1$X5L/agsv$Xdl0K/2IAHPefA.5jkKZo.
